language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: v3Qj2dBBRlsb4LKEZbtk7I3O0D36M6CRrEahWNAFtrwKqbNNa952EAZy4RKIT/bd7o+xKp8cii5ClhSWNgrT5FFZaAWGYbwFypwmB0d+COaA0zD4kLs3tTdIfK7Fu+rssP1EKxKXgDPI2tYNQhJzwvmRM0uD/JMB2NSuCB0E4xwtMq6ktlN2pM4eQVfQd5S1pPnmG9pbdtw7HUfcCtA5VyHjsDsNQGe0PzwsLdXBtzOiy2t3E0oShKzna5CzrGyCQAkOm13chXmiS3B7oRiq+Lieitp0Hw+91F7lJYt7DX6/rlsTLIAKsE0//bgX8cZxNL9h5Iiq98Qh+TqlSn/khqjctXTkzoVNxZwhUsMOmr87Ja1grUE50BXhd6+ekq4hR0gno1GMPLJFvy7WP2hTBUxG2OdFFtpaeCVlPHdg7cE0NWSynLULlFkap9hChRx3eRlFdz9/a2R/nEyWRwRTWSBW/NDtHSsyZrgua0D96S4g+KyusehfzYNRwqquk5C6vchQ2DRJYBgFzH5y9hLJbNZGnDsUlGelMvqBHq00GZPFvL+7KehZA7kK5tG8qqhi0VsuCtkBXNfGokB2Bt/3GWVtxnYwKPlhlgvjxsR88/ONj4U4EHU4ABzYD9O0jIsox1GTvGlPLRNMehtv8932asqsqo5PnyQTnjOOIJpUiqs=
  app: chronic-data
  on:
    repo: splnlss/chronic_data
