language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: O2Crini7GRLOrwZ65MeCS7erKtCmz2hU2Wgd0sNxXJ3eR8NonuMFtzBLpAKTy/La/kBS+F6WFJf3w8h+PnMZnMRgI/T8oHo12hwJZD58vxmFf+I7cu+JKRB6ObA7FI99qQcFalwRD2QfOALCh8LrXxHAkSEYRpJ0K9FLfKaJQrPPwiwLKmwZuMtnJ4td3ktyQkmvFRtoLjVqbN+3V/jbbH1grgXVw1OPP+aCzv/sxtPyVseWTPLuAYTrU+zwgKgTE+GxtN3YU+943ypXdiLVhuS7z4pMCyb8j8hui48bz9ZQUI3RE2aIcmcEYT8UmxcjLXJfz+Nut8uQj5YB/q2E5zNIJ8xbeLB8vgMsGKNxJxUFtuiXIF8K5EHL26HBq148ty0XtV1ZIa2PoqlEetmQMCBsAKiXYNzphV4dOowuaS/EzDQ+O0+hW92GhDIm5IXOlg9fEtWbNF3ToOn8lEgPkvJ0qHVPAQ36CFBMlyJUDyDE8RuvIEx3nE2En+l4mKRhE1wtmSVI5wEhlaJsYelvb6fkz7Q2RgI2jYO4l9n+YYailp2KPFA6r8fXW1blCGE9Y8hP1YN1IHMdgMUFRB8ZbowEDtZxH3SYGpu4iUF0QTc8dobRMujvDVfdJiDl+bcWiyHNhbdh7GEKw6aKjYMNzDiOxR+I0OPHKlNVmhQR0hs=
  app: chronic-data
  on:
    repo: splnlss/chronic_data
